### PR TITLE
Remove Vagrant setup and CFSSL reference

### PR DESCRIPTION
**Pull request by THS-on**
- remove CFSSL reference
- remove vagrant setup from main page

### CODE REVIEW

**Review by aplanas — APPROVED** [review]

**Comment by THS-on** [comment]
@maugustosilva  or @mpeters can we merge this?

**Comment by mpeters** [comment]
CFSSL I agree with removing, but are we sure we're ready to ditch the vagrant dev environment?

**Comment by THS-on** [comment]
> [...]  are we sure we're ready to ditch the vagrant dev environment?

Yes because currently it is broken and there is no maintainer for it. This confuses new users, when the first instructions on the website they find do not work. 

I think that @maugustosilva and @galmasi  are working on open sourcing their deployment tool, which we then can use in the future.

**Comment by maugustosilva** [comment]
@mpeters No one with bandwidth to maintain it. And yes, we got IBM approval to open-source our deployment tool, which is how we deploy (even "at scale") internally.

**Review by maugustosilva — APPROVED** [review]

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
